import { chromium, expect } from '@playwright/test';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import { preview } from 'vite';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('artifacts', { recursive: true });
const pdf = await PDFDocument.create();
const font = await pdf.embedFont(StandardFonts.Helvetica);
const page1 = pdf.addPage([612, 792]);
page1.drawText('A Local Reader for Research Papers', { x: 48, y: 725, size: 22, font });
page1.drawText('Abstract', { x: 48, y: 680, size: 14, font });
for (const [i, text] of ['This paper introduces a local reading assistant.', 'It translates research sentences into Korean.', 'The source document remains on the computer.', 'Hovering links the original sentence to its translation.'].entries()) page1.drawText(text, { x: 48, y: 650 - i * 19, size: 12, font });
const page2 = pdf.addPage([612, 792]);
for (const [i, text] of ['Left column begins', 'with a method that', 'runs on the computer.'].entries()) page2.drawText(text, { x: 48, y: 700 - i * 16, size: 12, font });
for (const [i, text] of ['Right column explains', 'the results of the', 'local experiment.'].entries()) page2.drawText(text, { x: 335, y: 700 - i * 16, size: 12, font });
pdf.addPage([612, 792]);
await writeFile('artifacts/sample-paper.pdf', await pdf.save());
const replacement = await PDFDocument.create(), replacementFont = await replacement.embedFont(StandardFonts.Helvetica);
replacement.addPage([612, 792]).drawText('Replacement document.', { x: 48, y: 700, font: replacementFont, size: 12 });
await writeFile('artifacts/replacement.pdf', await replacement.save());
const server = await preview({ preview: { host: '127.0.0.1', port: 4173 } });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [], remote = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (/^https?:/.test(r.url()) && !r.url().startsWith('http://127.0.0.1:4173/')) remote.push(r.url()); });
  await page.goto('http://127.0.0.1:4173');
  const actual = await page.evaluate(async () => ({ userAgent: navigator.userAgent, translator: typeof Translator, availability: typeof Translator === 'undefined' ? 'missing' : await Translator.availability({ sourceLanguage: 'en', targetLanguage: 'ko' }) }));
  console.log('Real isolated Chrome API probe:', actual);
  await page.screenshot({ path: 'artifacts/empty.png', fullPage: true });
  // Controlled adapter tests UI integration; these are not a real AI quality evaluation.
  await page.addInitScript(() => {
    window.__calls = 0; window.__models = 0; window.__delay = 70;
    indexedDB.open = () => { throw new Error('Simulated unavailable session storage'); };
    Object.defineProperty(window, 'Translator', { configurable: true, value: {
      availability: async () => 'downloadable',
      create: async ({ monitor }) => {
        window.__models++;
        if (window.__failModel) throw new DOMException('Simulated model unavailable', 'NotSupportedError');
        const events = new EventTarget(); monitor(events);
        const event = new Event('downloadprogress'); event.loaded = 1; events.dispatchEvent(event);
        return { destroy() {}, async translate(text, options) { window.__calls++; await new Promise(r => setTimeout(r, window.__delay)); if (options?.signal?.aborted) throw new DOMException('Aborted', 'AbortError'); return '로컬 번역 테스트: ' + text; } };
      }
    }});
  });
  await page.reload();
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.locator('.sentence')).toHaveCount(6);
  await expect(page.locator('.ai-status')).toContainText('번역 완료 · 3 / 3 페이지');
  expect(await page.evaluate(() => window.__calls)).toBe(8);
  // Replacing a document during inference must discard old asynchronous results.
  await page.evaluate(() => { window.__delay = 300; });
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.getByRole('button', { name: '번역 중단', exact: true })).toBeVisible();
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/replacement.pdf');
  await expect(page.locator('.ai-status')).toContainText('번역 완료 · 1 / 1 페이지');
  await expect(page.locator('.sentence')).toHaveCount(1);
  await expect(page.locator('.sentence p')).toHaveText('로컬 번역 테스트: Replacement document.');
  await page.evaluate(() => { window.__failModel = true; });
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.getByRole('alert')).toBeVisible();
  await expect(page.locator('.sentence')).toHaveCount(6);
  await page.evaluate(() => { window.__failModel = false; window.__delay = 20; });
  await page.getByRole('button', { name: '새로고침', exact: true }).click();
  await expect(page.locator('.ai-status')).toContainText('번역 완료 · 3 / 3 페이지');
  const originalSentences = await page.locator('.sentence p').evaluateAll(es => es.map(e => e.title || e.textContent));
  const originalViewport = await page.evaluate(() => ({ width: innerWidth, scale: devicePixelRatio }));
  const originalToolbar = await page.locator('.toolbar').boundingBox();
  const originalCanvas = await page.locator('[data-page="1"] canvas').boundingBox();
  await page.locator('.pdf-scroll').hover();
  await page.keyboard.down('Control'); await page.mouse.wheel(0, -100); await page.keyboard.up('Control');
  await expect(page.getByLabel('원문 배율 초기화')).toHaveText('122%');
  await expect(page.getByLabel('번역 배율 초기화')).toHaveText('100%');
  await expect.poll(async () => (await page.locator('[data-page="1"] canvas').boundingBox()).width).toBeGreaterThan(originalCanvas.width * 1.15);
  expect(await page.locator('.sentence p').evaluateAll(es => es.map(e => e.title || e.textContent))).toEqual(originalSentences);
  expect(await page.evaluate(() => ({ width: innerWidth, scale: devicePixelRatio }))).toEqual(originalViewport);
  expect((await page.locator('.toolbar').boundingBox()).height).toEqual(originalToolbar.height);
  await page.locator('.translation-scroll').hover();
  await page.keyboard.down('Control'); await page.mouse.wheel(0, -100); await page.keyboard.up('Control');
  await expect(page.getByLabel('번역 배율 초기화')).toHaveText('122%');
  await expect(page.getByLabel('원문 배율 초기화')).toHaveText('122%');
  expect(await page.locator('.sentence p').first().evaluate(e => parseFloat(getComputedStyle(e).fontSize))).toBeGreaterThan(16);
  await page.getByLabel('원문 배율 초기화').click(); await page.getByLabel('번역 배율 초기화').click();
  await expect(page.getByLabel('원문 배율 초기화')).toHaveText('100%');
  await expect(page.locator('.sentence.translated')).toHaveCount(6);
  await page.locator('.sentence').nth(2).hover();
  await expect(page.locator('.highlight-box').first()).toBeVisible();
  const highlight = await page.locator('.highlight-box').first().boundingBox();
  await page.mouse.move(highlight.x + highlight.width / 2, highlight.y + highlight.height / 2);
  await expect(page.locator('.sentence.active')).toHaveAttribute('data-sentence', 'p1-s2');
  const divider = page.getByRole('separator', { name: '원문과 번역 너비 조절' });
  const handle = await divider.boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 120);
  await page.mouse.down();
  await page.mouse.move(980, handle.y + 120, { steps: 12 });
  await page.mouse.up();
  await expect(divider).toHaveAttribute('aria-valuenow', '68');
  await expect.poll(async () => (await page.locator('.pdf-page-slot[data-page="1"] canvas').boundingBox()).width).toBeGreaterThan(950);
  await page.locator('.sentence').nth(2).hover();
  await expect(page.locator('.highlight-box').first()).toBeVisible();
  await page.screenshot({ path: 'artifacts/reader.png', fullPage: true });
  await page.reload();
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.locator('.sentence.translated')).toHaveCount(6);
  await expect(page.getByRole('separator')).toHaveAttribute('aria-valuenow', '68');
  await page.getByRole('separator').dblclick();
  await expect(page.getByRole('separator')).toHaveAttribute('aria-valuenow', '50');
  await expect(page.locator('.ai-status')).toContainText('번역 완료 · 3 / 3 페이지');
  expect(await page.evaluate(() => window.__calls)).toBe(8);
  expect(await page.evaluate(async () => (await indexedDB.databases()).map(d => d.name))).not.toContain('paper-lantern');
  await page.locator('.pdf-scroll').hover();
  await page.mouse.wheel(0, 1100);
  await expect(page.locator('.sentence')).toHaveCount(2);
  await expect(page.locator('.page-controls')).toContainText('2 / 3');
  await page.mouse.wheel(0, -1800);
  await expect(page.locator('.sentence')).toHaveCount(6);
  await expect(page.locator('.page-controls')).toContainText('1 / 3');
  await page.getByRole('button', { name: '다음 페이지', exact: true }).click();
  await expect(page.locator('.sentence')).toHaveCount(2);
  await expect(page.locator('.sentence p').first()).toHaveAttribute('title', 'Left column begins with a method that runs on the computer.');
  // Navigating never interrupts the document-wide queue. Explicit stop does.
  await page.evaluate(() => { window.__delay = 250; window.__calls = 0; window.__models = 0; });
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.getByRole('button', { name: '번역 중단', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '다음 페이지', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.__calls)).toBeGreaterThan(1);
  expect(await page.evaluate(() => window.__models)).toBe(1);
  await page.getByRole('button', { name: '번역 중단', exact: true }).click();
  const stoppedCalls = await page.evaluate(() => window.__calls);
  await page.waitForTimeout(350);
  expect(await page.evaluate(() => window.__calls)).toBe(stoppedCalls);
  await page.getByRole('button', { name: '새로고침', exact: true }).click();
  await expect(page.locator('.ai-status')).toContainText('번역 완료 · 3 / 3 페이지');
  await page.getByRole('button', { name: '다음 페이지', exact: true }).click();
  await expect(page.locator('.sentence')).toHaveCount(0);
  await page.reload();
  await expect(page.locator('.sentence')).toHaveCount(0);
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.locator('.ai-status')).toContainText('번역 완료 · 3 / 3 페이지');
  expect(await page.evaluate(() => window.__calls)).toBe(8);
  await page.getByLabel('PDF 파일 선택').setInputFiles({ name: 'invalid.pdf', mimeType: 'application/pdf', buffer: Buffer.from('not a PDF') });
  await expect(page.getByRole('alert')).toBeVisible();
  expect(errors).toEqual([]); expect(remote).toEqual([]);
  console.log('PASS: continuous wheel scrolling, current-page sync, drag resize, saved split, reset, PDF rendering, 2-column order, translation, bidirectional hover, auto model load, all-page translation, unavailable session storage fallback, stop/resume, scanned page, invalid PDF, no external requests.');
} finally { await browser.close(); await new Promise(resolve => server.httpServer.close(resolve)); }
