import { chromium, expect } from '@playwright/test';
import { preview } from 'vite';
const server = await preview({ preview: { host: '127.0.0.1', port: 4191, strictPort: true } });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } }), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => {
    window.__asked = [];
    Object.defineProperty(window, 'Translator', { value: { availability: async () => 'available', create: async () => ({ translate: async text => text, destroy() {} }) } });
    window.chrome ??= {}; window.chrome.runtime = { id: 'test', connect() {
      let closed = false; const messages = [], disconnected = [];
      return { onMessage: { addListener(f) { messages.push(f); } }, onDisconnect: { addListener(f) { disconnected.push(f); } }, disconnect() { if (!closed) { closed = true; disconnected.forEach(f => f()); } }, postMessage(m) {
        if (m.method === 'cancel') return;
        if (m.method === 'ask') window.__asked.push(m.params);
        const result = m.method === 'status' ? { protocolVersion: 7, models: [{ id: 'test', name: 'Test', isDefault: true }, { id: 'fast', name: 'Fast model', isDefault: false }] } : { answer: '## 핵심\n\n**강조**와 *기울임*.\n\n- 첫 항목\n- 둘째 항목\n\n> 인용문\n\n```python\nprint(1)\n```\n\n| 방법 | 값 |\n| --- | --- |\n| A | 1 |\n\n[자료](https://example.com)\n\n<script>window.injected=true</script>\n\n[위험](javascript:alert(1))', pages: [1, 2] };
        setTimeout(() => { if (!closed) messages.forEach(f => f({ id: m.id, result })); }, 30);
      } };
    } };
  });
  await page.goto('http://127.0.0.1:4191');
  await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.locator('.ai-status')).toContainText('번역 완료');
  await expect(page.getByLabel('질문 범위')).toHaveCount(0);
  const title = page.locator('[data-page="1"] .textLayer span').filter({ hasText: 'A Local Reader for Research Papers' }).first();
  await expect(title).toBeVisible(); const box = await title.boundingBox();
  await page.mouse.move(box.x + 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width - 2, box.y + box.height / 2, { steps: 10 }); await page.mouse.up();
  await page.getByRole('button', { name: 'Codex에게 질문', exact: true }).click();
  const popup = page.getByRole('dialog', { name: '선택한 부분 질문' });
  await expect(popup).toBeVisible(); await expect(page.locator('.chat-container')).toBeHidden();
  await expect(popup.locator('.selection-preview')).toContainText('Local Reader');
  await popup.getByLabel('논문 질문').fill('이 부분을 설명해줘'); await popup.getByRole('button', { name: '질문', exact: true }).click();
  await expect(popup.locator('.chat-message.assistant')).toHaveCount(1);
  await expect(popup.locator('.chat-markdown h2')).toHaveText('핵심');
  await expect(popup.locator('.chat-markdown li')).toHaveCount(2);
  await expect(popup.locator('.chat-markdown pre code')).toHaveText('print(1)');
  await expect(popup.locator('.chat-markdown table')).toHaveCount(1);
  await expect(popup.locator('.chat-markdown script')).toHaveCount(0);
  expect(await popup.locator('a').last().getAttribute('href')).not.toContain('javascript:');
  await expect(popup.locator('form').getByLabel('질문 모델')).toBeVisible();
  await popup.getByLabel('질문 모델').selectOption('fast');
  const request = await page.evaluate(() => window.__asked[0]);
  expect(request.pages).toHaveLength(3); expect(request.coverage).toBe('full'); expect(request.selection[0].text).toContain('Local Reader');
  const handle = popup.getByRole('button', { name: '선택 대화 이동' }); const before = await popup.boundingBox();
  await handle.focus(); await page.keyboard.press('ArrowRight'); await expect.poll(async () => (await popup.boundingBox()).x).toBe(before.x + 20);
  await page.screenshot({ path: 'artifacts/floating-chat.png' });
  await popup.getByRole('button', { name: '선택 대화 접기' }).click(); await expect(popup).toHaveCount(0);
  const chip = page.locator('.chat-chip'), chipButton = chip.locator('button').first();
  const folded = await chip.boundingBox();
  await page.mouse.move(folded.x+35,folded.y+15); await page.mouse.down();
  await page.mouse.move(folded.x+100,folded.y+45,{ steps: 5 });
  await expect(page.locator('.quote-source-highlight').first()).toBeVisible();
  const sourceBox = await title.boundingBox(), highlightBox = await page.locator('.quote-source-highlight').first().boundingBox();
  expect(Math.abs(sourceBox.y-highlightBox.y)).toBeLessThan(sourceBox.height / 2);
  await page.screenshot({ path: 'artifacts/chat-folded-highlight.png' });
  await page.mouse.up();
  await expect(popup).toHaveCount(0);
  expect((await chip.boundingBox()).x-folded.x).toBeCloseTo(65,0);
  await expect(page.locator('.quote-source-highlight')).toHaveCount(0);
  const scroller = page.locator('.pdf-scroll'), preScroll = await chip.boundingBox();
  await scroller.evaluate(el => el.scrollTop += 80);
  await expect.poll(async () => Math.round((await chip.boundingBox()).y-preScroll.y)).toBe(-80);
  await scroller.evaluate(el => el.scrollTop -= 80);
  const relativeBefore = await chip.evaluate(el => {const p=document.querySelector('[data-page="1"]');const a=el.getBoundingClientRect(),b=p.getBoundingClientRect();return {x:(a.x-b.x)/b.width,y:(a.y-b.y)/b.height};});
  await page.locator('.pdf-pages').evaluate(el => el.style.width='125%');
  await expect.poll(async () => chip.evaluate(el => {const p=document.querySelector('[data-page="1"]');return (el.getBoundingClientRect().x-p.getBoundingClientRect().x)/p.getBoundingClientRect().width;})).toBeCloseTo(relativeBefore.x,2);
  await page.locator('.pdf-pages').evaluate(el => el.style.width='100%');
  await chipButton.click(); await expect(popup.locator('.chat-message.assistant')).toHaveCount(1);

  await popup.getByLabel('논문 질문').fill('더 설명해줘'); await popup.getByRole('button', { name: '질문', exact: true }).click();
  await expect(popup.locator('.chat-message.assistant')).toHaveCount(2);
  expect(await page.evaluate(() => window.__asked[1].history.length)).toBe(2);
  expect(await page.evaluate(() => window.__asked[1].model)).toBe('fast');
  await popup.getByLabel('논문 질문').fill('저장할 질문 초안'); await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Codex 질문', exact: true }).click();
  const sidebar = page.locator('.chat-container');
  await sidebar.getByLabel('논문 질문').fill('논문 전체 핵심은?'); await sidebar.getByRole('button', { name: '질문', exact: true }).click();
  await expect(sidebar.locator('.chat-message.assistant')).toHaveCount(1);
  expect(await page.evaluate(() => window.__asked[2].selection)).toEqual([]);
  expect(await page.evaluate(() => window.__asked[2].pages.length)).toBe(3);
  await expect.poll(() => page.evaluate(() => new Promise(resolve => {
    const open = indexedDB.open('paper-lantern-sessions'); open.onsuccess = () => { const get = open.result.transaction('sessions').objectStore('sessions').getAll(); get.onsuccess = () => { resolve(get.result[0]?.selectionChats?.[0]?.draft); open.result.close(); }; };
  }))).toBe('저장할 질문 초안');
  await page.reload(); await page.getByLabel('PDF 파일 선택').setInputFiles('artifacts/sample-paper.pdf');
  await expect(page.locator('.chat-chip')).toHaveCount(1); await page.locator('.chat-chip button').first().click();
  await expect(popup.locator('.chat-message.assistant')).toHaveCount(2); await expect(popup.getByLabel('논문 질문')).toHaveValue('저장할 질문 초안');
  const sized = await popup.boundingBox();
  await page.mouse.move(sized.x + sized.width - 3, sized.y + sized.height - 3); await page.mouse.down();
  await page.mouse.move(sized.x + sized.width + 50, sized.y + sized.height + 30, { steps: 5 }); await page.mouse.up();
  expect((await popup.boundingBox()).width).toBeGreaterThan(sized.width);
  await popup.getByRole('button', { name: '선택 대화 접기' }).click();
  const again = await title.boundingBox();
  await page.mouse.move(again.x + 2, again.y + again.height / 2); await page.mouse.down();
  await page.mouse.move(again.x + again.width - 2, again.y + again.height / 2, { steps: 10 }); await page.mouse.up();
  await page.getByRole('button', { name: 'Codex에게 질문', exact: true }).click();
  await expect(popup.locator('.chat-message.assistant')).toHaveCount(0);
  await expect(page.locator('.chat-chip')).toHaveCount(1);
  await popup.getByRole('button', { name: '선택 대화 접기' }).click();
  await expect(page.locator('.chat-chip')).toHaveCount(2);
  await page.getByRole('button', { name: '선택 대화 삭제', exact: true }).last().click();
  await expect(page.locator('.chat-chip')).toHaveCount(1);
  await page.locator('.chat-chip button').first().click();
  await expect(popup.locator('.chat-message.assistant')).toHaveCount(2);
  await page.screenshot({ path: 'artifacts/chat-markdown.png' });
  expect(errors).toEqual([]);
  console.log('PASS: anchored PDF popup, folded drag/click, source highlight, scroll/zoom tracking, Markdown, model choice, conversations and session restore.');
} finally { await browser.close(); await new Promise(r => server.httpServer.close(r)); }
